/==============================================================/
/* Table: CIUDAD                                                */
/==============================================================/
/*CREATE TABLE CIUDAD (
   ID_CIUDAD            VARCHAR(5)            NOT NULL,
   ID_DEPTO             VARCHAR(2)            NOT NULL,
   NOMBRE               VARCHAR(20)           NOT NULL,
   CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD)
);*/

SCRIPT_CIUDAD
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Let','Ama', 'Leticia');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Med','Ant', 'Medellín');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Ara','Ara', 'Arauca');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Bar','Atl', 'Barranquilla');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Bog','Bog', 'Bogotá');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Car','Bol', 'Cartagena de Indias');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Tun','Boy', 'Tunja');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Man','Cal', 'Manizales');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Flo','Caq', 'Florencia');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Yop','Cas', 'Yopal');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Pop','Cau', 'Popayán');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Val','Ces', 'Valledupar');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Qui','Cho', 'Quibdó');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Mon','Cór', 'Montería');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Bog','Cun', 'Bogotá');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Iní','Gua', 'Inírida');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('San','Gua', 'San José del Guaviare');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Nei','Hui', 'Neiva');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Rio','La ', 'Riohacha');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('San','Mag', 'Santa Marta');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Vil','Met', 'Villavicencio');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Pas','Nar', 'Pasto');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('San','Nor', 'San José de Cúcuta');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Moc','Put', 'Mocoa');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Arm','Qui', 'Armenia');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Per','Ris', 'Pereira');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('San','San', 'San Andrés');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Buc','San', 'Bucaramanga');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Sin','Suc', 'Sincelejo');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Iba','Tol', 'Ibagué');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Cal','Val', 'Cali');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Mit','Vau', 'Mitú');
INSERT INTO CIUDAD (ID_CIUDAD,ID_DEPTO, NOMBRE)VALUES ('Pue','Vic', 'Puerto Carreño');