/*==============================================================*/

/* SQL DDL Table: DEPARTAMENTO */

/*==============================================================*/

/*CREATE TABLE DEPARTAMENTO (

ID_DEPTO VARCHAR(3) NOT NULL,

NOMBRE VARCHAR(20) NOT NULL,

CODIGO_TELEFONICO VARCHAR(10),

CONSTRAINT PK_DEPTO PRIMARY KEY (ID_DEPTO)

);*/


 INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Ama', 'COL', 'Amazonas');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Ant', 'COL', 'Antioquia');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Ara', 'COL', 'Arauca');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Atl', 'COL', 'Atlántico');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Bog', 'COL', 'Bogotá');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Bol', 'COL', 'Bolívar');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Boy', 'COL', 'Boyacá');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Cal', 'COL', 'Caldas');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Caq', 'COL', 'Caquetá');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Cas', 'COL', 'Casanare');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Cau', 'COL', 'Cauca');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Ces', 'COL', 'Cesar');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Cho', 'COL', 'Chocó');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Cór', 'COL', 'Córdoba');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Cun', 'COL', 'Cundinamarca');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Gua', 'COL', 'Guainía');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Gua', 'COL', 'Guaviare');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Hui', 'COL', 'Huila');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('La ', 'COL', 'La Guajira');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Mag', 'COL', 'Magdalena');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Met', 'COL', 'Meta');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Nar', 'COL', 'Nariño');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Nor', 'COL', 'Norte de Santander');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Put', 'COL', 'Putumayo');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Qui', 'COL', 'Quindío');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Ris', 'COL', 'Risaralda');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('San', 'COL', 'San Andrés y Providencia');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('San', 'COL', 'Santander');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Suc', 'COL', 'Sucre');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Tol', 'COL', 'Tolima');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Val', 'COL', 'Valle del Cauca');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Vau', 'COL', 'Vaupés');
INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('Vic', 'COL', 'Vichada');

