

/*==============================================================*/
/* Table: CIUDAD                                                */
/*==============================================================*/
/*CREATE TABLE CIUDAD (
   ID_CIUDAD            VARCHAR(5)            NOT NULL,
   NOMBRE               VARCHAR(20)           NOT NULL,
   CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD)
);*/





SCRIPT_CIUDAD
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Let', 'Leticia');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Med', 'Medellín');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Ara', 'Arauca');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Bar', 'Barranquilla');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Bog', 'Bogotá');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Car', 'Cartagena de Indias');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Tun', 'Tunja');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Man', 'Manizales');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Flo', 'Florencia');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Yop', 'Yopal');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Pop', 'Popayán');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Val', 'Valledupar');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Qui', 'Quibdó');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Mon', 'Montería');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Bog', 'Bogotá');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Iní', 'Inírida');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('San', 'San José del Guaviare');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Nei', 'Neiva');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Rio', 'Riohacha');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('San', 'Santa Marta');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Vil', 'Villavicencio');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Pas', 'Pasto');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('San', 'San José de Cúcuta');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Moc', 'Mocoa');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Arm', 'Armenia');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Per', 'Pereira');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('San', 'San Andrés');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Buc', 'Bucaramanga');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Sin', 'Sincelejo');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Iba', 'Ibagué');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Cal', 'Cali');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Mit', 'Mitú');
INSERT INTO CIUDAD (ID_CIUDAD, NOMBRE)VALUES ('Pue', 'Puerto Carreño');
