/*==============================================================*/
/* Table: PRODUCTOS                                             */
/*==============================================================*/
/*CREATE TABLE PRODUCTOS (
   ID_PRODUCTOS         VARCHAR(5)            NOT NULL,
   NOMBRE_PRODUCTO      VARCHAR(60),
   
   CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTOS)
);*/


SCRIPT_PRODUCTOS
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('1', 'Té Dharamsala');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('2', 'Cerveza tibetana Barley');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('3', 'Sirope de regaliz');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('4', 'Especias Cajun del chef Anton');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('5', 'Mezcla Gumbo del chef Anton');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('6', 'Mermelada de grosellas de la abuela');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('7', 'Peras secas orgánicas del tío Bob');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('8', 'Salsa de arándanos Northwoods');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('9', 'Buey Mishi Kobe');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('10', 'Pez espada');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('11', 'Queso Cabrales');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('12', 'Queso Manchego La Pastora');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('13', 'Algas Konbu');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('14', 'Cuajada de judías');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('15', 'Salsa de soja baja en sodio');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('16', 'Postre de merengue Pavlova');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('17', 'Cordero Alice Springs');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('18', 'Langostinos tigre Carnarvon');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('19', 'Pastas de té de chocolate');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('20', 'Mermelada de Sir Rodney's');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('21', 'Bollos de Sir Rodney's');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('22', 'Pan de centeno crujiente estilo Gustaf's');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('23', 'Pan fino');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('24', 'Refresco Guaraná Fantástica');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('25', 'Crema de chocolate y nueces NuNuCa');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('26', 'Ositos de goma Gumbär');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('27', 'Chocolate Schoggi');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('28', 'Col fermentada Rössle');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('29', 'Salchicha Thüringer');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('30', 'Arenque blanco del noroeste');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('31', 'Queso gorgonzola Telino');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('32', 'Queso Mascarpone Fabioli');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('33', 'Queso de cabra');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('34', 'Cerveza Sasquatch');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('35', 'Cerveza negra Steeleye');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('36', 'Escabeche de arenque');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('37', 'Salmón ahumado Gravad');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('38', 'Vino Côte de Blaye');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('39', 'Licor verde Chartreuse');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('40', 'Carne de cangrejo de Boston');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('41', 'Crema de almejas estilo Nueva Inglaterra');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('42', 'Tallarines de Singapur');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('43', 'Café de Malasia');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('44', 'Azúcar negra Malacca');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('45', 'Arenque ahumado');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('46', 'Arenque salado');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('47', 'Galletas Zaanse');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('48', 'Chocolate holandés');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('49', 'Regaliz');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('50', 'Chocolate blanco');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('51', 'Manzanas secas Manjimup');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('52', 'Cereales para Filo');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('53', 'Empanada de carne');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('54', 'Empanada de cerdo');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('55', 'Paté chino');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('56', 'Gnocchi de la abuela Alicia');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('57', 'Raviolis Angelo');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('58', 'Caracoles de Borgoña');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('59', 'Raclet de queso Courdavault');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('60', 'Camembert Pierrot');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('61', 'Sirope de arce');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('62', 'Tarta de azúcar');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('63', 'Sandwich de vegetales');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('64', 'Bollos de pan de Wimmer');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('65', 'Salsa de pimiento picante de Luisiana');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('66', 'Especias picantes de Luisiana');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('67', 'Cerveza Laughing Lumberjack');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('68', 'Barras de pan de Escocia');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('69', 'Queso Gudbrandsdals');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('70', 'Cerveza Outback');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('71', 'Crema de queso Fløtemys');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('72', 'Queso Mozzarella Giovanni');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('73', 'Caviar rojo');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('74', 'Queso de soja Longlife');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('75', 'Cerveza Klosterbier Rhönbräu');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('76', 'Licor Cloudberry');
INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE_PRODUCTO)VALUES ('77', 'Salsa verde original Frankfurter');


